trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACR_NAME: 'myacr'
  IMAGE_NAME: 'myapp'
  TAG: '$(Build.BuildId)'
  -group: ACR-Secrets  # This will fetch ACR_USERNAME and ACR_PASSWORD

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(TAG) .
        echo "$(ACR_PASSWORD)" | docker login $(ACR_NAME).azurecr.io -u $(ACR_USERNAME) --password-stdin
        docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(TAG)
      displayName: 'Build and Push Docker Image'


      