trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACR_NAME: 'acrdemoabb'
  IMAGE_NAME: 'sampleapp'
  AKS_RESOURCE_GROUP: 'Terraform-ABB-DEMO'
  AKS_CLUSTER_NAME: 'ABB_Demo_Cluster'
  - group: ACR-Secrets  # Fetch ACR credentials

parameters:
  - name: environment
    displayName: 'Select Deployment Environment'
    type: string
    default: 'dev'
    values:
      - dev
      - test
      - preprod
      - prod

variables:
  NAMESPACE: ${{ parameters.environment }}

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId) .
        echo "$(ACR_PASSWORD)" | docker login $(ACR_NAME).azurecr.io -u $(ACR_USERNAME) --password-stdin
        docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId)
      displayName: 'Build and Push Docker Image'

- stage: Deploy_to_AKS
  displayName: 'Deploy to AKS'
  jobs:
  - job: Deploy
    steps:
    - task: Kubernetes@1
      displayName: 'Login to AKS'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'Azure-Terraform-Connection'
        azureResourceGroup: '$(AKS_RESOURCE_GROUP)'
        kubernetesCluster: '$(AKS_CLUSTER_NAME)'
        useClusterAdmin: true

    - script: |
        echo "Deploying to Namespace: $(NAMESPACE)"
        kubectl apply -f deployment.yaml -n $(NAMESPACE)
        kubectl apply -f service.yaml -n $(NAMESPACE)
      displayName: 'Apply Kubernetes Deployment'
