trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACR_NAME: 'acrdemoabb'
  IMAGE_NAME: 'sampleapp'
  AKS_RESOURCE_GROUP: 'Terraform-ABB-DEMO'
  AKS_CLUSTER_NAME: 'ABB_Demo_Cluster'


parameters:
  - name: environment
    displayName: 'Select Deployment Environment'
    type: string
    default: 'dev'
    values:
      - dev
      - test
      - preprod
      - prod

variables:
  NAMESPACE: ${{ parameters.environment }}

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    steps:
    - task: Bash@3
      displayName: 'Build and Push Docker Image'
      inputs:
        targetType: 'inline'
        script: |
          echo "Building Docker image..."
          docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId) .
          
          echo "Logging in to ACR..."
          echo "$(ACR_PASSWORD)" | docker login $(ACR_NAME).azurecr.io -u $(ACR_USERNAME) --password-stdin
          
          echo "Pushing Docker image to ACR..."
          docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId)

- stage: Deploy_to_AKS
  displayName: 'Deploy to AKS'
  jobs:
  - job: Deploy
    steps:
    - task: Kubernetes@1
      displayName: 'Login to AKS'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'Azure-Terraform-Connection'
        azureResourceGroup: '$(AKS_RESOURCE_GROUP)'
        kubernetesCluster: '$(AKS_CLUSTER_NAME)'
        useClusterAdmin: true

    - task: Bash@3
      displayName: 'Deploy to AKS Namespace: $(NAMESPACE)'
      inputs:
        targetType: 'inline'
        script: |
          echo "Using Namespace: $(NAMESPACE)"
          kubectl apply -f deployment.yaml -n $(NAMESPACE)
          kubectl apply -f service.yaml -n $(NAMESPACE)
