trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: ACR-Secrets
  - name: TAG
    value: abb


parameters:
  - name: namespace
    displayName: 'Select Deployment Namespace'
    type: string
    default: 'nonprod'
    values:
      - nonprod
      - preprod
      - prod

  - name : acr_name
    displayName: ACR Name
    type: string
    default: 'acrdemoabb'
  
  - name : image_name
    displayName: Image Name
    type: string
    default: 'sampleapp'

  - name : cluster_name
    displayName: Cluster Name
    type: string
    default: 'ABB_Demo_Cluster'

  - name : resource_group
    displayName: Resource group Name
    type: string
    default: 'Terraform-ABB-DEMO'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        docker build -t ${{ parameters.acr_name }}.azurecr.io/${{ parameters.image_name }}:$(TAG) .
        echo "$(ACR_PASSWORD)" | docker login ${{ parameters.acr_name }}.azurecr.io -u $(ACR_USERNAME) --password-stdin
        docker push ${{ parameters.acr_name }}.azurecr.io/${{ parameters.image_name }}:$(TAG)
      displayName: 'Build and Push Docker Image'

- stage: Deploy_to_AKS
  displayName: 'Deploy to AKS'
  jobs:
    - job: Application_Deployment
      steps:
      - task: AzureKeyVault@2
        displayName: "Retrieve SPN Credentials from Key Vault"
        inputs:
          azureSubscription: "Azure-Terraform-Connection"
          keyVaultName: "terraformSecretsforABB"
          secretsFilter: "spn-tenant-id,spn-client-id,spn-client-secret,subscription-id"
  
      - task: Bash@3
        displayName: "Login to Azure using SPN"
        inputs:
          targetType: 'inline'
          script: |
            echo "Logging in to Azure using Service Principal"
            az login --service-principal \
              --username $(spn-client-id) \
              --password $(spn-client-secret) \
              --tenant $(spn-tenant-id)
            
            az account set --subscription $(subscription-id)
            
            echo "Successfully authenticated with Azure CLI"


            az aks get-credentials --resource-group ${{ parameters.resource_group }} --name ${{ parameters.cluster_name }} --overwrite-existing
          
            echo "Verifying AKS Connection"
            kubectl config current-context
            kubectl cluster-info
            kubectl get nodes
    
  
      - task: Bash@3
        displayName: "Set & Verify AKS Kubeconfig"
        inputs:
          targetType: 'inline'
          script: |
            kubectl config current-context
            kubectl cluster-info
      
      - script: |
          echo "Deploying to Namespace: ${{ parameters.namespace }}"
          kubectl create secret docker-registry acr-secret \
          --docker-server=$(ACR_USERNAME).azurecr.io \
          --docker-username=$(ACR_USERNAME) \
          --docker-password=$(ACR_PASSWORD) \
          --namespace=${{ parameters.namespace }}

          kubectl apply -f deployment.yaml -n ${{ parameters.namespace }} --validate=false
          kubectl apply -f service.yaml -n ${{ parameters.namespace }} --validate=false
          sleep 15
          kubectl get svc myappabb-service -n ${{ parameters.namespace }}
          echo " Get the External IP of the sevice and access the application in your browser"
        displayName: 'Apply Kubernetes Deployment (Validation Off)'

