apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappabb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myappabb
  template:
    metadata:
      labels:
        app: myappabb
    spec:
      containers:
        - name: myappabb
          image: acrdemoabb.azurecr.io/sampleapp:95
          imagePullPolicy: Always
          ports:
            - containerPort: 3000  # This is where your app listens
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: acr-secret
