apiVersion: v1
kind: Service
metadata:
  name: myappabb-service
spec:
  selector:
    app: myappabb  # Ensure this matches the label of the pods in your deployment
  ports:
    - protocol: TCP
      port: 80            # External port (access via this port)
      targetPort: 3000     # Internal port where the app is listening
  type: LoadBalancer      # Expose app via LoadBalancer (use NodePort if internal access is enough)
